### ISSUE TITLE
[assertj] Global assert entry-points

### ISSUE THREAD

**Issue by kriegfrj** [osgi/osgi-test#115]
Creating a new issue to capture discussion that began in a pull request here: https://github.com/osgi/osgi-test/pull/110#discussion_r424813029 Thought that the discussion was important enough that it be captured in a top-level issue for posterity rather than buried somewhere as an appendage to another PR.

In summary, we think it might be a good idea on balance to have an "uber soft assertion provider" interface which amalgamates all of the individual soft assertion providers into a single interface. Probably, the same arguments apply (to a lesser degree) to have an `Assertions` class that contains entry points for the hard assertions.

One question still to be resolved is where to put these uber-classes. Given the package versioning stability issues that @bjhargrave is justly concerned about, it would probably best if they were put in their own package. A couple of candidates:

* org.osgi.test.assertj
* org.osgi.test.assertj.api

_Edit: fixed link_

**Comment by bjhargrave** [comment]
> A couple of candidates:
> 
>     * org.osgi.test.assertj

This is probably the best candidate.

>     * org.osgi.test.assertj.api

I don't care for this one since `api` is rather vauge.

Or `org.osgi.test.assertj.soft`?

**Comment by kriegfrj** [comment]
> > A couple of candidates:
> > ```
> > * org.osgi.test.assertj
> > ```
> 
> This is probably the best candidate.
> 

I tend to agree. 

> > ```
> > * org.osgi.test.assertj.api
> > ```
> 
> I don't care for this one since `api` is rather vauge.
> 

I tend to agree. I was trying to follow the AssertJ convention but it didn't follow exactly anyway as all the assertion code was in subpackages of api.

> Or `org.osgi.test.assertj.soft`?
 Rules out creating a hard assertion entry point.

**Comment by kriegfrj** [comment]
Having mulled this over further...

Perhaps we can go an intermediate route. The OSGi bundle/package hierarchy is not as flat as what we have here. It would make sense to have (either instead of, or in addition to) individual aggregated soft assertions providers for each of the OSGi bundles. We can create subpackages corresponding to each bundle, move the assertions for that bundle into the corresponding subpackage, and have a soft assertions provider at the top-level package for each one. `PromisesSoftAssertionsProvider` for all classes in `org.osgi.util.promise`, and a `FrameworkSoftAssertionsProvider` for all classes in `org.osgi.framework`, etc. Minor problem is we might end up with name collisions as some packages and classes have the same name, but they'll be in different packages so shouldn't be an issue. There's likely to be more of a correlation between needing to use assertions in each bundle rather than across the whole of OSGi.
