### ISSUE TITLE
[assertj] Soft assertions proxy generating references to non-imported packages

### ISSUE THREAD

**Issue by kriegfrj** [osgi/osgi-test#118]
I started trying to use the newly-added soft proxies implementation of the `Bundle`, `BundleEvent` and `BundleContext` assertions. However, I found that the dynamically-generated soft assertions proxy classes have references to AssertJ core classes that are not statically referenced in the class files themselves. This means that bnd doesn't include them in `Import-Package` and the soft assertion class fails to load at runtime with `NoClassDefFoundError`. In my case, it was `org.assertj.core.api.recursive.comparison.RecursiveComparisonConfiguration`.

Possible solutions that I see:
* Manually add Import-Package filter to cover all of the core assertj packages (possibly as optional imports).
* Ditto but use DynamicImport-Package
* A Bnd plugin that can analyze the class files to find all instances of proxy generation invocation, run them, and examine the dependencies of the generated classes, and include those in the import-package analysis (Rolls-Royce!)

I tried the first two but only succeeded in getting rid of the default Import-Package statement. I tried using the syntax `Import-Package: org.assertj.core.api.recursive.comparison, *` only succeeded in ending up with an Import-Package statement that included only `org.assertj.core.api.recursive.comparison`. Ditto - when I tried `DynamicImport-Package: *`, the `Import-Package` statement disappeared completely.

**Comment by kriegfrj** [comment]
Managed to figure out what i was doing wrong and now I've got the Import-Package working. Maybe we should also be doing full in-framework integration testing of our AssertJ bundle to catch these.

**Comment by bjhargrave** [comment]
> Maybe we should also be doing full in-framework integration testing of our AssertJ bundle to catch these.

That is probably a necessary thing since the purpose of these is to use for in-framework integration testing. We should be confident that it works well.
