### ISSUE TITLE
Split org.osgi.test.assertj into org.osgi.test.assertj.framework and org.osgi.test.assertj.promise

### ISSUE THREAD

**Issue by bjhargrave** [osgi/osgi-test#149]
Having PromiseAssert in the bundle means all users must provide the promise/function packages. This is unfortunate in the OSGi compliance tests for those test which are not otherwise touching promise.

Since we may make more custom assertj asserts for other packages, we should probably have a unique artifacts for each package.

**Comment by kriegfrj** [comment]
One bundle per bundle or one per package?

**Comment by bjhargrave** [comment]
Two artfacts: org.osgi.test.assertj.framework and org.osgi.test.assertj.promise for now.

If we do, for example, custom assertions for ConfigurationAdmin, we would then create a new artifact for that: org.osgi.test.assertj.cm.
