### ISSUE TITLE
[junit4] Define an OSGi service rule

### ISSUE THREAD

**Issue by rotty3000** [osgi/osgi-test#18]
Depending on OSGi services in tests can be tricky, with a nice JUnit4 rule/JUnit5 extension that eliminates the boiler plate and helps assert the invariants the problem can be greatly simplified.

**Comment by kriegfrj** [comment]
I have a simple JUnit 4 rule in my own test library that you could use to register services as you go, and then it would automatically unregister them at the end of every test. It would not be hard to make it a JUnit 5 extension too.

Unless you already have something more elaborate planned/implemented that you are imminently ready to contribute, I'm happy to contribute what I have as a starting point.

**Comment by rotty3000** [comment]
That's the second impl I've been offered today :D

Gimme a bit to finish the first pass on mine and of it's terrible we can
look at yours and the other one that was sent to me ;)

**Comment by rotty3000** [comment]
Fixed by https://github.com/osgi/osgi-test/pull/21
