### ISSUE TITLE
Register Jupiter extensions globally (discussion)

### ISSUE THREAD

**Issue by kriegfrj** [osgi/osgi-test#200]
I've been thinking a little about the usage of our extensions.

All of our extensions are quite non-invasive. They won't do a lot if you haven't explicitly annotated your tests with the relevant `@Injectxxx` annotation(s).

Perhaps we should consider registering the Jupiter extensions globally? This should be possible simply by registering them as OSGi services with the `Extension` component type. In this way, you could dispense with the `@ExtendWith` annotation - it will be sufficient to use the `@Injectxxx` annotations.

The only downside to this (that I can see) is the extra execution overhead - each extension needs to run a pass over the fields in the test class to see if any have fields that it is interested in. If your class doesn't use the extension then that is extra overhead you could otherwise avoid.

Thoughts?

**Comment by bjhargrave** [comment]
So biz.aQute.tester.junit-platform already registers Extension services?

Not sure this is worth it and it puts us in the code path of tests which have no OSGi specific testing going on.

**Comment by rotty3000** [comment]
Note a strong opinion here, but I lean toward a preference to be explicit in the use of things rather than hide them. It's also much easier for someone not familiar with the code to come by and see a more complete picture.

**Comment by rotty3000** [comment]
Furthermore, extensions support inheritance so you could "hide" the extension up on a single parent class to reduce the "noise" if that's your goal.

**Comment by kriegfrj** [comment]
> So biz.aQute.tester.junit-platform already registers Extension services?
> 

No,  but it should work with the addition of the right config parameter, add long as you've got SPI-Fly installed in the framework. 

> Not sure this is worth it and it puts us in the code path of tests which have no OSGi specific testing going on.

That is also a concern of mine.

**Comment by kriegfrj** [comment]
> Furthermore, extensions support inheritance so you could "hide" the extension up on a single parent class to reduce the "noise" if that's your goal.

As an aside, it would be better to hide it on an implemented interface rather than a parent class because you can still get multiple inheritance that way. But still, that doesn't reduce the noise too much as you have to remember to inherit/implement the parent class/interface.

I guess it's more of a convenience thing. I can see a head-scratching moment for some people if they've annotated `@InjectBundleContext` but forgotten the `@ExtendWith` or `@RegisterExtension`. Automatically registering the extension would be a way around that. But then, they still have to remember to configure Jupiter to allow auto-registration.

On balance, I think I'm leaning towards not worrying about it. The gain is minor and as @bjhargrave pointed out it puts our extensions in the way for tests that aren't even using them. I'll leave the issue open for a while longer in case anyone has some additional thoughts, and if there's no strong opinion one way or the other I'll close it.

**Comment by kriegfrj** [comment]
There doesn't seem to have been a strong opinion either way, so I'm closing. We can always reopen if a compelling use case becomes apparent in the future.
