### ISSUE TITLE
assertj assertions for org.osgi.framework.Bundle

### ISSUE THREAD

**Issue by rotty3000** [osgi/osgi-test#22]
I can see this pattern occurring frequently in your tests. I've used similar patterns a lot in my own tests.

If we had `org.osgi.test.assertj` up-to-date, then the above could simplify to (eg) `assertThat(installedBundle).isInState(Bundle.UNINSTALLED)`. I can see this pattern getting used a lot so perhaps we should look at an AssertJ assertion class for `Bundle` sooner rather than later.

_Originally posted by @kriegfrj in https://github.com/osgi/osgi-test/diffs_

**Comment by kriegfrj** [comment]
This issue was implemented by #50. Unfortunately I used "implements" in the commit message (instead of "fixes" or "closes", etc) which is not one of the keywords that GitHub automatically recognises for auto-closing issues.
