### ISSUE TITLE
[common] CloseableBundleContext to handle superclass methods

### ISSUE THREAD

**Issue by kriegfrj** [osgi/osgi-test#23]
Was running some tests using the `BundleContextRule` and found that it blew up when I tried to call `toString()` on the proxied bundle context.

Looking at the code, it seems that `invoke()` will only handle method calls for methods declared in the `AutoCloseable` and `BundleContext` interfaces. For any other method call, it will throw `IllegalArgumentException`. This includes method calls for inherited methods, such as those inherited from `Object` and `BundleReference`. By a happy coincidence, the only method declared in `BundleReference` (`getBundle()`) is also declared in `BundleContext` (though without the `@Override` tag - should it have it?), so it still works. However, the methods of `Object` code would rightly expect to be available too.

For `CloseableBundleContext` to do the best possible job of masquerading as a true `BundleContext`, it needs to ensure that it handles all method calls.

Fix to come.

**Comment by rotty3000** [comment]
The fix was merged.
