### ISSUE TITLE
Inject ServiceProperties

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi-test#235]
Would it be useful for `osgi-test` to inject the ServiceProperties of an `@InjectService` annotated Service into an MethodParameter?

Here some Examples:

```
@ExtendWith(ServiceExtension.class)
public class ServicePropertyInjectionTest {

	@BeforeAll
	public static void beforeAll(@InjectBundleContext BundleContext bundleContext) throws Exception {
		bundleContext.registerService(Foo.class, new Foo() {}, Dictionaries.dictionaryOf("a", "b"));
		bundleContext.registerService(Bar.class, new Bar() {}, Dictionaries.dictionaryOf("c", "d"));
	}

	@Test
	public void testWithServiceAwareWildcardParameter(@InjectService Foo foo, Map<String, Object> fooProperties)
		throws Exception {
		assertThat(foo).isNotNull();
		assertThat(fooProperties).isNotNull()
			.containsEntry("a", "b");
	}

	@Test
	public void testWithServiceAwareWildcardParameter(@InjectService Foo foo, Map<String, Object> fooProperties,
		@InjectService Bar bar, Map<String, Object> barProperties) throws Exception {
		assertThat(foo).isNotNull();
		assertThat(fooProperties).isNotNull()
			.containsEntry("a", "b");

		assertThat(bar).isNotNull();
		assertThat(barProperties).isNotNull()
			.containsEntry("a", "b");
	}

	@Test
	public void testWithServiceAwareWildcardParameter(@InjectService Foo foo, @InjectService Bar bar,
		Map<String, Object> barProperties) throws Exception {
		assertThat(foo).isNotNull();

		assertThat(bar).isNotNull();
		assertThat(barProperties).isNotNull()
			.containsEntry("a", "b");
	}

}
```

**Comment by rotty3000** [comment]
`ServiceAware.getServiceReference().getProperties()` is close, but it might be nice to have the convenience to directly inject them. Although I think you'd have to also use the @InjectService on the field/parameter, it's just too awkward to implement otherwise.

**Comment by stbischof** [comment]
If also the `@InjectService`  on the field/parameter would be needed, `ServiceAware.getServiceReference().getProperties()` would be the much easier way.

**Comment by bjhargrave** [comment]
We seem to be getting closer to reinventing DS here...

**Comment by kriegfrj** [comment]
What about if we allow the ability to inject the `ServiceReference` object directly as an alternative? Just thinking out loud.

**Comment by bjhargrave** [comment]
> What about if we allow the ability to inject the `ServiceReference` object directly as an alternative?

We already support injecting `ServiceAware` which gives access to everything. Injecting a `ServiceReference<T>` or a `Map<String,Object>` is just convenience. Both can be done.

**Comment by stbischof** [comment]
I tried a lot and most cases could be handled better by using assertj propperly with `ServiceAware`.

there is one case i really like to get injected easier.
the number of the httpservice-port. Any ideas on that?

**Comment by bjhargrave** [comment]
> the number of the httpservice-port. Any ideas on that?

There should not be special treatment for a particular service property. If you really want to continue to emulate DS behavior :-) you could support coercion of service properties to types like [Component Property Types](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.component.html#service.component-component.property.types).

**Comment by stbischof** [comment]
I think we can close this here. Thank You for discussion
