### ISSUE TITLE
ServiceAware  should provide acces to ServiceTrackerCustomizer

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi-test#237]
Suppose I inject a ServiceAware at the beginning of my test case, and I expect cardinality of 1.

Then, at some point during the test, I create a configuration, which should cause another service of the same type to get activated. How can I set the ServiceAware instance to make it wait till also the second service arrives?
I tried with waitForService, but it returns immediately because one service is already there... (because it is the first one)

It would be great to have a way  to wait for a defined count of services. Without loop over `getServices` and `Thread.sleep`
`List<T> waitForServices(long timeout, int cardinality) throws InterruptedException;`

**Comment by rotty3000** [comment]
couldn't you just setup a second ServiceAware with card=0 and then use that in the test to _wait_ for the dynamically added service?

**Comment by rotty3000** [comment]
... use filters of course to distinguish between service instances.

**Comment by stbischof** [comment]
If I dives a bit deeper, i see that we also need From ServiceAware something like 
```
int getRemovedCount();
int getModifiedCount();
int getAddingCount();
```
[ExampleCode](https://github.com/stbischof/osgi-test/commit/6318fe3c46460f4e3d3b88a6cdad06cdd1175900)

But at the end it might be better to just use a ServicetrackerCustomizer that you can get from the ServiceAware.
Maybe it would be a way to add the Method `Class<? extends ServiceTrackerCustomizer<?, ?>> serviceTrackerCustomizerClass();`to the `@InjectService` Annotation.

Then i can ask my customizer.

**Comment by bjhargrave** [comment]
I think this is beginning to over complicate ServiceAware which is a layer over ServiceTracker. Adding such features will require extensive tests to make sure the changes are accurate and thread-safe.

If you need something beyond ServiceAware, perhaps you need to fall back to your own ServiceTracker usage?

**Comment by stbischof** [comment]
I came up with this approach because the ServiceConfiguration hat still an Delegation mechanism to an ServicetrackerCostumizer. You only need a way to set these.

The original needs came from developers that switched the testsframework to osgi tests. And asked for this features.

**Comment by kriegfrj** [comment]
What if `ServiceAware` had an overloaded `waitForService(long timeout, int cardinality)` method where you can override the default number of services to wait for? Just a thought. (Sorry for being late to the party on this one...)

**Comment by stbischof** [comment]
At the Moment i would prefere this https://github.com/osgi/osgi-test/pull/245 for the most of my testing use cases. Here i can check all changes.

But there is still the one case where i am just have some services and wait for more.

**Comment by bjhargrave** [comment]
Can we now close this?
