### ISSUE TITLE
[junit4] Resolution not picking up new dependency

### ISSUE THREAD

**Issue by kriegfrj** [osgi/osgi-test#24]
I'm not sure if this is an osgi-test configuration issue, or a Bndtools/m2e issue, but:

I added Mockito as a test dependency. When I look at the Resolution window for `org.osgi.test.junit4-1.0.0-SNAPSHOT-test.jar`, it is correctly declaring `org.mockito` as an import. However, when I ran the resolver on `test.bndrun`, it failed to pick up Mockito as a required bundle.

**Comment by rotty3000** [comment]
See how Junit5 uses mockito.
