### ISSUE TITLE
Refactor Configuration reset behavior 

### ISSUE THREAD

**Issue by juergen-albert** [osgi/osgi-test#279]
As discussed today with @stbischof:

The Test tries to reset Configurations to a state before the test started. This currently happens by a best guess approach. A better solution could look as follows:
1. Take a snapshot of the Configurations the `ConfigurationAdmin` knows about before a test starts.
2. Record all the `ConfigurationsEvent`s that appear during a test runs
3. Try to reverse them in the order received.

While writing this down and thinking about it, I came to the point that this is error prone as well, because this would catch all configuration changes that happen during a test and not only the changes that someone directly does in the a test. Instead of magically trying to catch a `ConfigurationEvent`s and reverting them, I believe we should only revert changes a test causes directly by interacting with the `ConfigurationAdmin`. 
An Example why: We have the real case, where we have a configurable Component that in turn creates/updates a couple of other configurations if it receives a configuration. It also takes care of cleanup and changes. If this would happen during a test, the reset mechanism could in theory mess up the build in mechanism to handle configurations handled by this component. (Yes, one could argue that it should be robust enough to handle external manipulation of configurations, but no).

In our tests, we have one central point we use to handle configurations, so we can clean up what we have done after the test has finished. Maybe here something different is possible, by providing a change aware `ConfigurationAdmin`. This could be a complete Wrapper around the actual Service that records what the user does and that can be reverted afterwards.

**Comment by stbischof** [comment]
somethink like [CloseableBundleContext](https://github.com/osgi/osgi-test/blob/main/org.osgi.test.common/src/main/java/org/osgi/test/common/context/CloseableBundleContext.java).

**Comment by juergen-albert** [comment]
Exactly!

**Comment by bjhargrave** [comment]
So you proposed to provider the bundle-under-test a "wrapped" ConfigurationAdmin service so you can "see" what the bundle-under-test does and unwind it? What if there are multiple bundles in the test scenario? Not just the bundle with the test classes? Will you give all the bundles the wrapped ConfigurationAdmin service? In this scenario, ConfigurationAdmin is a database. For the purposes of testing, you need to set the database to some known state and then run the tests. After the tests you can attempt to restore the database to the state it was in before being set to some known state.

**Comment by juergen-albert** [comment]
No really. I though more along the line of something like this over simplified:

```
@Test
public void myTest(@InjectService ServiceAware<ConfigurationAdmin> wrappedConfigAdmin){
    wrappedConfigAdmin.getService().ca.getFactoryConfiguration(...)
    .
    .
    .
}
```
The Wrapped Configuration Admin would only be injected and used in a Test and nowhere else. The goal would be to only role back the changes somebody makes directly in the test. Cleanup of other things downstream must be handled by the bundles and components that do the changing.

**Comment by bjhargrave** [comment]
A closeablebundlecontext makes sense since the test case will install any bundles it needs. But if the test case installs bundles and those bundle manipulate config admin, then only supplying a wrapped config admin to the test case does not accomplish your goal of resetting config admin to some state that existed before the test was run.
