### ISSUE TITLE
[junit4] ServiceUseRule race condition

### ISSUE THREAD

**Issue by kriegfrj** [osgi/osgi-test#28]
The tests for `ServiceUseRule` are intermittently failing.

After a detailed look at this, I think I have nailed down the cause:

* `ServiceUse` relies on the `ServiceTracker`'s `addingService()` event to keep track of when services are added.
* However, the `addingService()` event is fired *before* the service is actually added to the tracker's map:

https://github.com/eclipse/rt.equinox.framework/blob/1f5b39b749d49214e2383c1333cf8603a1da604e/bundles/org.eclipse.osgi/osgi/src/org/osgi/util/tracker/AbstractTracked.java#L255-L269

So when `ServiceUse`s' `addingService()` method returns, it hasn't actually appeared in the map yet, and so won't be visible in the list of tracked bundles.

The flow of `addingService()` makes sense - the purpose of a customizer is to have a chance to customize which services are added to the tracker. However, it means it is not that useful for our intended purpose.

Unfortunately the `ServiceTracker` doesn't seem to have any kind of `addedService()` event (called after the put() statement), and the object that it is waiting on is private. The only solution I can think of is to poll until `tracker.count() == cardinality`, but I'm open to other suggestions.

**Comment by bjhargrave** [comment]
>     * However, the `addingService()` event is fired _before_ the service is actually added to the tracker's map

Well of course since the addingService method can return `null` to reject tracking the service.

**Comment by kriegfrj** [comment]
> Well of course since the addingService method can return `null` to reject tracking the service.

Yes, makes perfect sense when you think about it!
