### ISSUE TITLE
use osgi test bom in examples

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi-test#289]
When we release the bom we should use it in the example.

https://github.com/osgi/osgi-test/blob/main/examples/osgi-test-example-mvn/pom.xml

**Comment by bjhargrave** [comment]
Why? Boms can be useful but I am not sure we want to use it here, do we?

**Comment by juergen-albert** [comment]
Does it hurt to have one ? I would say no and it makes live easier for maven users.

**Comment by bjhargrave** [comment]
I am not saying not to have a bom (although I think the current bom overspecifies the versions of JUnit and some other osgi jars; it should really only talk about the osgi-test jars). I am questioning whether it is wise to modify the example to use the bom.
