### ISSUE TITLE
Add at least a minimal example to the wiki

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi-test#300]
Currently the wiki only list the releases, but a minimal example would be nice to present there, or even a link to some blog-posts.

**Comment by laeubi** [comment]
For example the maven-bnd-exampel could be linked there: https://github.com/rotty3000/osgi-test-example-mvn
as well as https://www.eclipsecon.org/2020/sessions/easier-integration-testing-osgi-open-source-osgi-test-project

**Comment by bjhargrave** [comment]
We moved the example into _this_ repo, https://github.com/osgi/osgi-test/tree/main/examples/osgi-test-example-mvn, after the EclipseCon presentation.

**Comment by stbischof** [comment]
There also is a pre bnd-gradle-layout version in this pr https://github.com/osgi/osgi-test/pull/247

**Comment by kriegfrj** [comment]
Added a reference to the examples directory in the wiki page.
