### ISSUE TITLE
"TimeWarp" extension

### ISSUE THREAD

**Issue by kriegfrj** [osgi/osgi-test#315]
This is a bit of a pie-in-the-sky idea, but I think it could turn into something useful. Just throwing this out there for now in case there are any other ideas about potential design.

I hit a strange case with my test today: I had some code with a bug in it - it was parsing times using "hh:mm:ss" (12h) format when it should have been using "HH:mm:ss" (24h) format. But the parser was forgiving and still accepted hours >=13. So most of the time it worked - the only issue was times between [12:00:00,13:00:00) - they were interpreted as 12am rather than 12pm, which produced the incorrect result. I only discovered the bug by accident when I happened to be running the relevant test around noon.

The main problem with the test design is that it was dependent on an external, uncontrolled factor - the system time. But this was unavoidable because the code-under-test is an expiry algorithm and so it is dependent on system time too. Tests should always try and control the external factors to produce repeatable results.

Completely coincidentally, I got another notification today which reminded me of a feature in Robolectric - its code-weaving classloader modifies code-under-test so that all calls to `System.currentTimeMillis()` would be routed through itself. This gave it the opportunity to return a different value if desired. It wasn't perfect, but it enabled you to do some simple tests changing the system time on-the-fly.

I believe something similar could be done with OSGi-test using code-weaving hooks. Or possibly using an agent approach to get lower-level access to `System.currentTimeMillis()`.

Issues that would need to be worked out:

1. Code libraries that are used on both sides of the "fence" that separates test code from code-under-test. I think this could be handled by instrumenting them, and then when the call to `System.currentTimeMillis()` is intercepted the library could examine the stack trace to see which side of the "fence" the call originates from.
2. Code in system libraries that cannot be instrumented by OSGi code-weaving hooks - eg, core Java system libraries, OSGi framework. Perhaps a Java agent could be used here instead, I'm not sure how feasible this is.
3. Interaction with other time-dependent libaries and methods in the JDK (eg, `Thread.sleep()` and various other functions that have a timeout). A simple implementation of the timewarp extension could focus on `System.currentTimeMillis()` which would facilitate simpler tests, and a more complex implementation could look at a more comprehensive integration with other system calls later.

I anticipate two components:
1. The core (in `org.osgi.test.common`) which provides the time-warping functionality.
2. A JUnit 5 extension (and if there is sufficient demand, a JUnit 4 rule counterpart) that takes care of installing a time warp at the beginning of each test and removing it at the end.

**Comment by bjhargrave** [comment]
At some level, this is a mocking problem. You want to mock the time (to be something other than the actual time) for certain parties under test.

It seems a narrow testing problem that would require a substantial effort to support. 

It would be easier for testing if you write your code to use the `java.time.Clock` class to access the time instead of `System.currentTimeMillis()`. Then your test can created a `FixedClock` (via `Clock.fixed`) and then pass that into the code under test. Then there is no need for special weaving magic to test code with desired time values.

**Comment by kriegfrj** [comment]
I've tried that approach before. It can work in some circumstances. But the problem is that you need all your code to use the same clock (even 3rd party libraries). Using `System.currentTimeMills()` is too entrenched.

**Comment by bjhargrave** [comment]
I would assume you would use simple unit testing to catch these sorts of errors in time formatting (as you described above). So you don't need a big stick of weaving calls to currentTimeMillis in a running system for that purpose. Needing to set the time to some value for a larger system is hard. Time travel is always dangerous :-)

**Comment by kriegfrj** [comment]
I tend not to bother with unit tests and focus on integration tests... I find that unit tests have two flaws in general:
1. They rely heavily on mocking, and the tests are only as accurate as the mocks that you use (integration, in contrast, prefers real implementations). Over time, the accuracy of the mocks fails as the real objects (the ones they are meant to be representing) change.
2. with unit tests, you end up more focused on testing a specific implementation rather than the higher-level functional requirements. When (not if) during your integration stage you realise that you need to significantly change the implementation, you find that the units need a significant rework and all the tests along with them.

Sure, unit tests usually run faster. But it doesn't matter how fast they run if they are not accurate or if they are testing stuff that doesn't really need to be tested. Just my 2c. :smile:

**Comment by bjhargrave** [comment]
There is a place for both. Unit tests are very useful to test a specific API. That can be fast and comprehensive and can enforce semantic details of the API. Integration tests are then good to layer over to make sure multiple things work together. But they mostly only indirectly test APIs and thus cannot comprehensively test the API since the code driving the API is only driving it in the way that code uses the API.

**Comment by kriegfrj** [comment]
Ok, let me clarify: the goal should be to test the public interface.

If you're writing a module/library with an API that is intended for direct public consumption, then I agree - you need to test all possible uses of the API. In such cases, the unit test is really an integration test.

But if (as is often the case) your unit is an internal building block of your system, you don't have to test all possible uses - you only have to test the uses that you need for your application. Integration tests do this well. It doesn't matter if they cannot comprehensively test parts of the API that you're not actually using in your application. In fact, if it is difficult for you to test parts of the internal API through your integration tests, this is often a sign (in my experience) that you didn't really need that functionality in the internal API in the first place. I've found that if you focus too much on the units and testing them you can too easily fall into this trap of writing unnecessary code to implement and test unnecessary functionality.
