### ISSUE TITLE
[common] Unnecessary type safety violation in asMap()

### ISSUE THREAD

**Issue by kriegfrj** [osgi/osgi-test#327]
I was reviewing #326 when I took a closer look at `Dictionaries.asMap()`.

The method as it currently stands seems to unnecessarily leave open the potential for type safety violations. The following code snippet demonstrates the possibility:

```java
Hashtable<Integer, Integer> intMap = new Hashtable<>();
Map<Number, Number> castMap = Dictionaries.asMap(intMap);
castMap.put(1.0, 1.9);
```

The above code compiles, and allows the caller to put floats into the underlying hashtable even though it was declared to accept only integers. Goodness only knows what kind of issues this might introduce further down the code path.

The fix for this is simple enough: the bounded wildcards on the dictionary need to be removed from `asMap()` so that the type parameters on the incoming dictionary exactly:

current:
```java
	public static <K, V> Map<K, V> asMap(Dictionary<? extends K, ? extends V> dictionary) {
```
new:
```java
	public static <K, V> Map<K, V> asMap(Dictionary<K, V> dictionary) {
```

This prevents the above code from compiling.

I'm struggling to the see the use case for including the bounds on the parameter to `asMap()`, but I raised this ticket in case someone else sees the need. If there is a genuine use case for it, I suggest that we push the burden of doing the unsafe cast back to the caller, eg:

```java
Hashtable<Integer, Integer> intMap = new Hashtable<>();
Map<Number, Number> castMap = Dictionaries.asMap((Dictionary<Number, Number>)intMap);
castMap.put(1.0, 1.9);
```
or:
```java
Hashtable<Integer, Integer> intMap = new Hashtable<>();
Map<Number, Number> castMap = (Map<Number, Number>)Dictionaries.asMap(intMap);
castMap.put(1.0, 1.9);
```

That way, if the caller wants to do something silly like this for whatever reason, at least the potential for compile-time type safety circumvention will be made explicit in their code. With the current API, we are hiding the type safety circumvention behind our own unsafe cast.

Because this is a breaking change (albeit a completely justifiable one IMO), I feel that it would be good to try and squeeze this into the 1.0 release (if possible) by cherry picking it?

**Comment by bjhargrave** [comment]
> Because this is a breaking change (albeit a completely justifiable one IMO), I feel that it would be good to try and squeeze this into the 1.0 release (if possible) by cherry picking it?

I cherry-picked this onto the release branch for 1.0.0. Thanks!

**Comment by tjwatson** [comment]
Does `org.osgi.framework.FrameworkUtil.asMap(Dictionary<? extends K, ? extends V>)` have the same issue?

**Comment by bjhargrave** [comment]
> Does `org.osgi.framework.FrameworkUtil.asMap(Dictionary<? extends K, ? extends V>)` have the same issue?

Yes. But I think the issue is mostly theoretical. I think most users of asMap/asDictionary will be using it to provide a view over something for reading and not writing. And I do not think most users will modify the generic type.

We can look to fix for FrameworkUtil too. It is a source-incompatible change rather than a binary-incompatible change.

**Comment by kriegfrj** [comment]
Yes, @bjhargrave is correct, it's mostly theoretical. I just pity the first person who inadvertently puts the theory into practice. 😄
