### ISSUE TITLE
take the executorRule from the test harness and make it an official rule

### ISSUE THREAD

**Issue by rotty3000** [osgi/osgi-test#35]
> Although it perhaps goes beyond the scope of osgi-test, there is a lot about proper osgi testing that involves concurrency. I think we should consider making these executor-related extensions/rules part of the public API. There are also some concurrency-related utilities I wrote as part of the bnd tester testing that have generic application (eg, waiting for another thread to enter the wait state) that could form part of a concurrency testing library. That can be a topic for another issue/PR though; happy for it to be test-only scope for now.

_Originally posted by @kriegfrj in https://github.com/osgi/osgi-test/pull/34_

**Comment by rotty3000** [comment]
I think what we should actually do is make the executor rule use the PromiseFactory so that it returns promises instead of futures.

**Comment by bjhargrave** [comment]
Actually, the down side of this is that we may use a different version of promises from the one used by the user. Perhaps it is better that we don't require any OSGi API in our test support implementation?

**Comment by rotty3000** [comment]
perhaps you're right

**Comment by rotty3000** [comment]
Closing since I think this won't happen and I've seen not strong need for it.

**Comment by kriegfrj** [comment]
I'm writing a test at the moment in which I'm trying to initiate concurrent method calls to check that my read-write locking mechanism is doing the right thing. I've been doing it by manually starting threads, but then I have to be concerned about trying to stop them all at the end of the test. It occurred to me that something like an `ExecutorExtension` would be useful for that - I can simply schedule all the threads as background threads and the extension will take care of stopping them all for me. The only thing is that it doesn't seem to properly belong in "osgi" test, as such an extension is not OSGi-specific. But I wouldn't know where else to put it at the moment.

Are we happy for it to live in osgi-test?

**Comment by bjhargrave** [comment]
For an executor, you can close it when the test ends. But you will also need a way to signal to each thread to terminate. There is no way to generally and reliably do this from some sort of standard extension. So I don't see that we can author such an extension.
