### ISSUE TITLE
nested jar-packaging in tests files also includes the classes

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi-test#381]
@bjhargrave 
I expected that this [bnd instruction](https://github.com/osgi/osgi-test/blob/733f76d78a6656d40c715168e595927a6a74ee89/org.osgi.test.junit5/pom.xml#L119) tells bnd to not include in the `org.osgi.test.junit5.test.tb1` package into the `org.osgi.test.junit5-tests.jar` but it is there.

when changing the eclusion pattern to `**/tb1/**` it works

```
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
			...
				<excludes>
					<exclude>**/tb1/**</exclude>
				</excludes>
			...
			</plugin>
```

**Comment by rotty3000** [comment]
this should work:
```xml
<exclude>org/osgi/test/junit5/tb*/**</exclude>
<exclude>org/osgi/test/junit5/test/tb*/**</exclude>
```
Why not just remove the second `/test/` package part to match the existing pattern?

**Comment by rotty3000** [comment]
FYI, this is not a bug. It is by design.

However, if you wish to use the bnd workspace approach to using bnd instructions to cause resources to be in the final jar, you need to set the `<includeClassesDir>false</includeClassesDir>`.
