### ISSUE TITLE
[build] Build loop

### ISSUE THREAD

**Issue by kriegfrj** [osgi/osgi-test#406]
Looks like we have a build loop in m2e again. I can't recall the exact circumstances of how it happened, but I had the `org.osgi.test.assertj` project open and noticed that `org.osgi.test.common` listed in the Maven Dependencies container for this project was being repeatedly rebuilt - alternating between "without test classes" and no decoration message.

I wonder if this is caused by the introduction of `org.osgi.test.stubs` in #403?

**Comment by bjhargrave** [comment]
I think we can closed this as a bug in m2e which has been fixed in m2e 1.18.2.
