### ISSUE TITLE
Do not substitutably import the org.osgi.test.common.annotation package in junit5

### ISSUE THREAD

**Issue by bjhargrave** [osgi/osgi-test#489]
This causes the resolver to bring in both junit4 and junit5 since
the both export and import the package. This is an issue when using the
bom when both junit4 and junit5 jars are available to the resolver.

**Comment by bjhargrave** [comment]
I found this when moving the examples to 1.1.0 and the resolver was including junit4 when the tests only used/needed junit5. 

We may want to consider fixing this in a 1.1.1 maintenance release.

**Comment by kriegfrj** [comment]
> We may want to consider fixing this in a 1.1.1 maintenance release.

👍 

Regarding the actual fix: I'm not familiar with the syntax you've used, but would it be possible to reuse/coopt the JUnit capability namespace we defined to achieve the same purpose, rather than create something new?

**Comment by bjhargrave** [comment]
> but would it be possible to reuse/coopt the JUnit capability namespace we defined to achieve the same purpose

I don't know what you mean. The fix I made here was simply to not import the exported `org.osgi.test.common.annotation` package by adding `substitution = Substitution.NOIMPORT` to the `Export` annotation. This has nothing to do with namespaces.

**Comment by bjhargrave** [comment]
Also need to include 5005c67e8a447ca1bf4fe25be87c102515e6bd7c. That is, only the junit5 bundle needs to not substitutably import the org.osgi.test.common.annotation package while the junit4 bundle must substitutably import the org.osgi.test.common.annotation package. Then if both bundles are present in the resolve solution, the package is chosen from the junit5 bundle.

**Comment by kriegfrj** [comment]
> > but would it be possible to reuse/coopt the JUnit capability namespace we defined to achieve the same purpose
> 
> I don't know what you mean. 

Well, that makes two of us! 😉 

> The fix I made here was simply to not import the exported `org.osgi.test.common.annotation` package by adding `substitution = Substitution.NOIMPORT` to the `Export` annotation. This has nothing to do with namespaces.

Ok, I'm just not sure what the `attribute="junit=4` is supposed to achieve here (similarly for junit5):

`@Export(attribute = "junit=4", substitution = Substitution.NOIMPORT)`

My comment pertained to that attribute.

After closer inspection (on a full-sized screen!), I just realised that this is not part of the current PR - that the attribute was already present. So I guess my comment, while perhaps still worthy of some consideration, does not directly apply to this issue or PR.

**Comment by bjhargrave** [comment]
I added the `junit=4` and `junit=5` attributes to the exports when we first duplicated the package so that someone could specify the `junit` attribute on an import if they wished to select a specific copy of the package.

Let's wait a little bit to make a 1.1.1 release with this fix in case some other issue comes forward. I have updated Bnd and OSGi builds to use 1.1.0 and they seem fine so far.

**Comment by kriegfrj** [comment]
> Let's wait a little bit to make a 1.1.1 release with this fix in case some other issue comes forward. I have updated Bnd and OSGi builds to use 1.1.0 and they seem fine so far.

:+1: Do you think it is worth it to have the 1.1.1 release branch ready to go and then we can cherry-pick any other fixes if they come forward? That way, if someone comes forward who needs 1.1.1 urgently we'll be ready to ship it in short order.
