### ISSUE TITLE
[ServiceExtension] Tweak wildcard type inferencing for upper bounds

### ISSUE THREAD

**Issue by kriegfrj** [osgi/osgi-test#494]
I happened to be looking through the code for `ServiceExtension` and noticed that the recent change to the type inferencing (added in 7d932f5ba1ec1) has some flaws:

https://github.com/osgi/osgi-test/blob/b5f1603a4536f54e9109656475c372997d5421f5/org.osgi.test.junit5/src/main/java/org/osgi/test/junit5/service/ServiceExtension.java#L100-L102

`Object.class` will not be the correct choice when an upper bound has been set on the wildcard. Eg, if the parameter/field type is `List<? extends Date>`, then `Date` is probably the most appropriate choice rather than `Object`. Using `Object` risks causing `ClassCastException` at runtime.

**Comment by kriegfrj** [comment]
> This was already the case. The change only relocated that test to a new place.
>

Sorry, you're right - I cut-pasted the wrong revision hash.
 
> Checking the bound of the wildcard has its limits. `<? extends Date>` will likely show as `Date` for the upper bound. But when you encounter `<? extends T>`, you will then need to see if you can compute a bound for `T` which may not be possible if the declaring class does not declare the bound.
>

Indeed, checking the bound has limits. If the bound is not a concrete class, then you'll get the "Service must have non-generic type" error - as you would if the parameter .
 
> Again, is this really that important? The situation is a test coding error. But in this situation we cannot catch a CCE since we are injecting a collection and the cast will occur at the call sites in the test code.

It is precisely because no CCE is thrown at the point where the error actually happens (and that a bomb is left to detonate later), that makes this even more important.

> Since this is about test writing, I think we need to err on the side of letting people shoot themselves in the foot rather than preventing them from doing something potentially dangerous. If what they do is in fact dangerous, they will find out. But it is possible they know what they are doing and need to do something unusual that we should not pedantically prohibit.

1. The problem is that the *default* behaviour in this situation was an exercise in foot-shooting. The following code would generate CCE:
```java
@InjectService
List<? extends Date> services;

@Test
void myTest() {
    Date d = services.get(0); // Will probably throw ClassCastException
}
```
It will not be obvious to the user why the above code throws a CCE, nor what they would need to do to fix it. To avoid the CCE, they'd need to do this:
```java
@InjectService(service=Date.class)
List<? extends Date> services;

@Test
void myTest() {
    Date d = services.get(0); // Now we're safe
}
```
It's one thing to allow a developer to shoot themselves in the foot - it's another to have the gun pointing at the developer's foot by default. :smile:

2. Yes, sometimes when writing tests you need to do unusual or "dangerous" things to trigger possible bugs. However, the point of writing test code is to exercise the *code-under-test*, not to exercise the test code itself - so when you do these "dangerous" things, you're typically doing it to the code-under-test, not the test code. IMO, test code itself should follow best practice as far as possible - that way when a failure occurs you know it is most likely because of a failure in the code you are testing rather than failure in the code that is trying to test it.
3. This patch (and #495) doesn't stop developers shooting themselves in the foot if they really want to. If they really want their test code to generate a CCE, they can inject into (eg) a `List<?>` or `ServiceAware<?>` and cast it to whatever incompatible type that they want:
```java
@InjectService(service=AtomicBoolean)
List<?> services;

@Test
void myTest() {
    List<? extends Date> unsafeServices = (List<? extends Date>)services; // Will generate "unchecked cast" type safety warning
    Date d = unsafeServices.get(0); // Will throw ClassCastException
}
```
This will at least generate a suitable compiler warning so the developer will be alerted to the fact that they're doing something dangerous instead of doing it by accident and without warning.

I strongly feel that good, timely sanity checking that produces helpful diagnostics like this is an important part of a polished API. Accidental misconfigurations like this might happen rarely, but when they do happen that can cause significant time wasted with head scratching if the diagnostics aren't helpful. This is the guiding principle behind the use of AssertJ instead of simply using `assertTrue()` everywhere

If I had the time, I would even go so far as to write an annotation processor so that you can do these sanity checks at compile time and with pretty IDE integration, like I did for [Robolectric](https://github.com/robolectric/robolectric/tree/master/processor) years ago. But in the absence of support for compile-time checking, finding and reporting such misconfigurations at the earliest possible opportunity at runtime is the next best thing.

**Comment by bjhargrave** [comment]
> ```java
> @InjectService
> List<? extends Date> services;
> ```

Why would a test writer do that instead of `List<Date>`? There is almost no utility in using bound for a list like this in a test. What purpose does the `? extends` serve for the test writer? You almost never want to use wildcards on fields or method return values. They are interesting for method arguments since it allows the API designer to provide maximum freedom to the API user. But in a test case, I don't see why you would want your List/ServiceAware with a wildcard.

**Comment by kriegfrj** [comment]
> > ```java
> > @InjectService
> > List<? extends Date> services;
> > ```
> 
> Why would a test writer do that instead of `List<Date>`? There is almost no utility in using a wildcard for a list like this in a test. What purpose does the `? extends` serve for the test writer? You almost never want to use wildcards on fields or method return values. They are interesting for method arguments since it allows the API designer to provide maximum freedom to the API user. But in a test case, I don't see why you would want your List/ServiceAware with a wildcard.

Just a moment ago you were saying we should let the developer do "dangerous" things if they want to. :smile:

But this is a very good point. I agree, I would not use a wildcard in this context. But the code as I found it sort-of supported this syntax, but in a way that would cause errors.

I think the way forward is to decide if we're going to support this syntax or not.

* If we're going to support it, then we should support it properly as I have done.
* If we're not going to support it, then we should throw a configuration exception if we detect the usage of a bounded wildcard (leave the unbounded case as that was supported historically).

Thoughts?
