### ISSUE TITLE
osgi-test-example-mvn / org.osgi.test.example.player.test.PlayerTest are not executed

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi-test#499]
1. I check out the repository
2. I edit the file https://github.com/osgi/osgi-test/blob/main/examples/osgi-test-example-mvn/org.osgi.test.example.player.test/src/test/java/org/osgi/test/example/player/test/PlayerTest.java and add `throw new RuntimeException();` to the `PlayerTest.beforeAll(BundleContext)` and expect the test to fail
4. Instead the build succeeds, I see the following output in the maven console:
> [INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ org.osgi.test.example.player.test ---
[INFO] Tests are skipped.

**Comment by kriegfrj** [comment]
You need to run the bnd-testing-pmaven-plugin, not the surefire plugin. Reference: https://github.com/bndtools/bnd/blob/master/maven/bnd-testing-maven-plugin/README.md

**Comment by laeubi** [comment]
@kriegfrj probably yes... but it seems the example is not configured that way. 
The [README](https://github.com/osgi/osgi-test/tree/main/examples/osgi-test-example-mvn) dos not mention any special maven call either.

**Comment by kriegfrj** [comment]
Sorry for being a bit terse,  don't have time for an in-depth response and was hoping to point you in the right direction. If you run "mvn verify" it should execute all the goals for you including the bnd plugin test. Alternatively, you can launch from within Eclipse.

**Comment by laeubi** [comment]
> If you run "mvn verify" it should execute all the goals for you including the bnd plugin test

Alright, thanks for the hint, I have tried it only with "mvn test" and seem to be confused by the skipped test output... Now everything runs fine!
