### ISSUE TITLE
Need to obtain code coverage reports and interactive debugging within intellij and gradle plugin

### ISSUE THREAD

**Issue by catshow** [osgi/osgi-test#513]
Is there a way to get code coverage and interactive debugging from osgi-test within intelli-j (I am using the gradle bnd plugin)?

1. I would like to be able to run a specific test, by right clicking on it.
2. I want to be able to see how much coverage I have from running the tests.

Thanks

**Comment by bjhargrave** [comment]
There is nothing specific in osgi-test for code coverage. I assume you would need to use some existing test coverage tool like jacoco or something. @kriegfrj may be know more here.

As for interactive debugging, I use Bndtools which has a "Bnd OSGi Test Launcher" Run/Debug option which you can use on the bndrun files and then run/debug your tests.

<img width="597" alt="image" src="https://user-images.githubusercontent.com/277682/164732093-6c2b2613-0888-4704-a320-249ba51c9252.png">

**Comment by catshow** [comment]
Unfortunately bndtools is an eclipse only thing.  I am currently running the debugger with this in my test-debug.bndrun file:

```
-include=./test.bndrun
-runjdb: 10001
```

then I have to fire up the remote JVM debugger in intellij.  This is not a convenient workflow.

I think that what is needed is an implementation of a gradle [TestFramework](https://github.com/gradle/gradle/blob/master/subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/TestFramework.java), that could be configured with a bndrun file. 

I think this would also allow one to run a specific test method and not the entire test suite.  Additionally, I believe it would solve the problem of having to create a whole separate integration project, because the TestFramework should receive the actual classes and methods that it needs to run.

Thanks for your consideration.

**Comment by bjhargrave** [comment]
> I think that what is needed is an implementation of a gradle [TestFramework](https://github.com/gradle/gradle/blob/master/subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/TestFramework.java), that could be configured with a bndrun file.

Why not use the `TestOSGi` gradle task type? https://github.com/bndtools/bnd/tree/master/gradle-plugins#create-a-task-of-the-testosgi-type

As TestFramework is an internal Gradle type, I don't see Bnd Gradle plugins making use of it.

**Comment by catshow** [comment]
I do use the TestOSGi like this:

I have a separate debug task that use the -jdb, otherwise it will get hung up in CI builds.

```kotlin
val resolveTask = tasks.register<aQute.bnd.gradle.Resolve>("resolve") {
    dependsOn(tasks.compileTestJava)
    description = "Resolve test.bndrun"
    group = "test"
    bundles.from(configurations.testRuntimeClasspath)
    bndrun.set(file("test.bndrun"))
    outputBndrun.set(layout.buildDirectory.file("test.bndrun"))
}

val testOSGiTask = tasks.register<aQute.bnd.gradle.TestOSGi>("testOSGi") {
    dependsOn(resolveTask)

    description = "OSGi Test test.bndrun"
    group = "test"
    bndrun.set(resolveTask.flatMap { it.outputBndrun })
}

val debugResolveTask = tasks.register<aQute.bnd.gradle.Resolve>("debugResolve") {
    dependsOn(resolveTask)

    description = "Resolve test.bndrun"
    group = "test"
    bndrun.set(file("test-debug.bndrun"))
    outputBndrun.set(layout.buildDirectory.file("test-debug.bndrun"))
}

val debugTestOSGiTask = tasks.register<aQute.bnd.gradle.TestOSGi>("debugTestOSGi") {
    println("to find an existing java debug listening on a port use the following command")
    println("netstat -vanp tcp | grep 10001")

    dependsOn(debugResolveTask)

    // always run
    outputs.upToDateWhen { false }
    description = "OSGi Test test-debug.bndrun"
    group = "test"
    bndrun.set(debugResolveTask.flatMap { it.outputBndrun })
}

```
It is unfortunate that it is an internal type.  :-(. 

I guess I will look at maybe implementing an intellij plugin that can provide a junit platform launcher.

@bjhargrave is there a bnd gradle task that will generate a workspace, that will take a configuration.  Also is there a way to specify a workspace within the bndrun file?

**Comment by bjhargrave** [comment]
> is there a bnd gradle task that will generate a workspace, that will take a configuration. 

No. 

> Also is there a way to specify a workspace within the bndrun file?

Normally, in a non-Bnd workspace model build like gradle, there is no Bnd Workspace and the bndrun file will be provisioned with a "standalone" workspace. What do you need from a Bnd Workspace?

**Comment by catshow** [comment]
@bjhargrave 

> > Also is there a way to specify a workspace within the bndrun file?
> 
> Normally, in a non-Bnd workspace model build like gradle, there is no Bnd Workspace and the bndrun file will be provisioned with a "standalone" workspace. What do you need from a Bnd Workspace?

I am trying to use eclipse, now.  The right click run BND OSGi test launcher fails, because I don't have a workspace.  I would like to generate one based on the gradle configurations, instead of manually building one.

**Comment by bjhargrave** [comment]
So I imported the gradle example project in this repo into an Eclipse workspace and Bnd launcher fails. Bndtools need more work to support launching bndrun files in a plain gradle project. We did work for maven support in the Bndtools m2e feature. I guess we need to do similar work for gradle to integrate with Buildship. You can open an issue in the bndtools/bnd repo to note this missing support.

**Comment by bjhargrave** [comment]
So I imported the gradle example project in this repo into an Eclipse workspace and Bnd launcher fails. Bndtools need more work to support launching bndrun files in a plain gradle project. We did work for maven support in the Bndtools m2e feature. I guess we need to do similar work for gradle to integrate with Buildship. You can open an issue in the bndtools/bnd repo to note this missing support.
