### ISSUE TITLE
@ServiceSource should support ServiceAware<ServiceType>

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi-test#594]
`@ServiceSource` currently supports `ServiceReference<ServiceType>` and `ServiceType` (according to my tests as there is no javadoc...) but having `ServiceAware<ServiceType>` would be good as well.

**Comment by kriegfrj** [comment]
@laeubi, thank you so much for this contribution - however, based on the current information I'm inclined to agree with @bjhargrave 's assessment on the utility of your proposed feature. The point of `@ServiceSource` is to specify a collection of services to use one-at-a-time as the value for the parameter in the parameterized test. A `ServiceAware`, on the other hand, *is* a collection of services. As @bjhargrave pointed out, you can get a single `ServiceAware` injected as a parameter already if that's what you want:

```java
@Test
void myTest(@InjectService(cardinality=3) ServiceAware<MyServiceType> s) {
}
```

Do you have a specific use case in mind where you felt that combining `ServiceAware` with `@ServiceSource` could be useful? Eg, perhaps if you specified an array of filters to `@ServiceSource`, then the service source parameter could generate a `ServiceAware` corresponding to each filter in turn?

**Comment by laeubi** [comment]
@kriegfrj I'm not remembering directly why I was requiring this, I think it was while refactoring some OSGi-TCK, **but** the crucial part here might be:

> there is no javadoc...

So maybe it would help to describe what it is used for and the possible alternatives and in what situation one should choose which annotations, its often hard to decide so probably it was just the wrong choice at that time.

**Comment by kriegfrj** [comment]
I sympathise with the "no javadoc" (or perhaps more generally, "no doc") - I wish I personally had more time to sort that out.

In light of your comment, I will close this issue - but if something specific comes to mind and you feel it's worth revisiting this, please feel free to let us know.

Thank you so much for your help (even issues that are ultimately rejected are still helpful).
