### ISSUE TITLE
google/truth vs assertj

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi-test#60]
Is the assertion Framework fixed to AssertJ or is Google Truth an option?

https://github.com/google/truth

**Comment by bjhargrave** [comment]
We are using assertj for the tests here. And there is a folder for custom assertj assertions. If you want to contribute a folder for custom google truth support for OSGi, please make PRs. I don't think it is either one or the other.

**Comment by kriegfrj** [comment]
Ditto what @bjhargrave said. Osgi-test currently comprises four bundles, and only one of them is directly tied to AssertJ. I see no reason why there couldn't also be an `org.osgi.test.truth` bundle if there was a willing contributor too.
