### ISSUE TITLE
[cm] Support Systemproperties in Property

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi-test#614]
Currently one can use the following construct:

```
@WithFactoryConfiguration(factoryPid = ServerRuntime.NAME, name = "testme", properties = {
			@Property(key = "port", value = "9999") })
```
This is great unless the port should be able to be set from the outside (e.g. different test-systems might have the port already allocated, e.g. on CI or dev maschine)

It would therfore be good to support an additional property `systemProperty` in the `@Property` annotation that  evaluates the given name as a system Property e.g.:

```
@WithFactoryConfiguration(factoryPid = ServerRuntime.NAME, name = "testme", properties = {
			@Property(key = "port", value = "9999", systemProperty = "test.port") })
```

if the process is run with `-Dtest.port=1234` the the value should actually be derived as `System.getProperty("test.port", <value>)`

**Comment by stbischof** [comment]
I recomment to use config-admin plugin ([specified here](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.cm.html#i1459884
)) 

Felix has plugins can do the job [link](https://github.com/apache/felix-dev/tree/6603d69977f4cea8b9b9dd2faf5d320906b43368/configadmin-plugins/interpolation) 
this is better suppoert like `"$[env:PORT;type=Integer[];delimiter=,;default=8080,8081]"`

or you register it by your one

**Comment by laeubi** [comment]
I don't think that a plugin is the right choice here and only complicates things, because in that case I can simply delete the annotation all together and use an own plugin anyways :-)
The Felix plugin is great for a runtime but for test all the options are not required, e.g overriding the value of a parameter by system property is very common by maven-plugins and works for the majority of cases well enough.

**Comment by laeubi** [comment]
Seems still an issue.
