### ISSUE TITLE
[cm] either create unbound config, or provide an option for it.

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi-test#615]
Currently the annotation performs the following:

```
if (Property.NOT_SET.equals(configAnnotation.location())) {
   configuration = configurationAdmin.getFactoryConfiguration(configAnnotation.factoryPid(),
	configAnnotation.name());
} else {
   configuration = configurationAdmin.getFactoryConfiguration(configAnnotation.factoryPid(),
	configAnnotation.name(), configAnnotation.location());
}
```

that way configurations are either require an **explicit** location or are bound to the "calling bundle" (what is the test probe) and is most likely not desired by default.

This should be changed to using a `null` location, or if it is absolutely desired, at least a boolean flag to do so.

See [104.4.2 Dynamic Binding ](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.cm.html#d0e11038)

another option would be to not use `Property.NOT_SET` but `?` as the default value...

**Comment by stbischof** [comment]
@timothyjward what is your opinion on that?
i would prefere `Property.NOT_SET`

**Comment by timothyjward** [comment]
`Property.NOT_SET` is correct, but that should result in setting a null location. 

@laeubi could you write a test case for this?
