### ISSUE TITLE
Provide a possibillity to inject and empty configuration where update has not been called yet

### ISSUE THREAD

**Issue by maho7791** [osgi/osgi-test#780]
If I declare something like this:

```
@InjectConfiguration(withFactoryConfig = @WithFactoryConfiguration(factoryPid = "Blub", location = "?", name = "test"))
Configuration clientConfig;
```
The update is automatically called before starting my test. I would like to have to option to do that at some point in my test, by providing the corresponding properties and trigger the update. This would need to have a trigger to disable the configuration by default using a field in the @InjectConfiguration annotation..
```
@InjectConfiguration(withFactoryConfig = @WithFactoryConfiguration(factoryPid = "Blub", location = "?", name = "test"), enabled = false)
Configuration clientConfig;
```

It is clear that this can only work for empty configurations. 
The benefit would be having these configrations tracked as well and beeing cleaned up automatically afterwards.

**Comment by timothyjward** [comment]
I agree with the use case, but disagree with the `enabled` property.

If someone specifies

    @InjectConfiguration(withFactoryConfig = 
        @WithFactoryConfiguration(factoryPid = "Blub", location = "?", name = "test"))

Then the `properties` are `NOT_SET`. This should mean that the configuration is *not* updated, and I think that if it is being updated that that is a bug.

Do you feel up to making a PR for this?

**Comment by maho7791** [comment]
I'll take a look into it

**Comment by stbischof** [comment]
@maho7791 

did you test this with the new snapshot?

https://github.com/osgi/osgi-test/blob/32fbf7437d9451464e54782af019cd10c18300ef/org.osgi.test.junit5.cm/src/main/java/org/osgi/test/junit5/cm/ConfigurationExtension.java#L480

**Comment by maho7791** [comment]
I'll check this out

**Comment by maho7791** [comment]
I made a short test and it worked with @WithConfiguration but not with @WithFactoryConfiguration.

This test fails with cs == null:

```
static final String MY_PID = "my.fpid";

@Test
@WithFactoryConfiguration(factoryPid = MY_PID)
public void testMethodConfigurationFactoryEmtpy() throws Exception {

	Configuration cs = ConfigUtil.getConfigsByServicePid(ca, MY_PID);
	assertThat(cs).isNotNull();

}
```
The config is in the configuration manager, but it cannot be found using the provided filter in `ConfigUtil.getConfigsByPid'. This belong to the name that was generated by config admin.


This test succeeds:

```
static final String MY_OTHER_PID = "my.other.pid";

@Test
@WithFactoryConfiguration(factoryPid = MY_OTHER_PID, name = "myname")
public void testMethodConfigurationFactoryNameEmtpy() throws Exception {

	Configuration cs = ConfigUtil.getConfigsByServicePid(ca, MY_OTHER_PID + "~myname");
	assertThat(cs).isNotNull();

}
```

I also debugged both test cases and realized that The update method was called in both tests:
https://github.com/osgi/osgi-test/blob/744cb395c1d4bd5407ea172467c4ce37579ed8ba/org.osgi.test.junit5.cm/src/main/java/org/osgi/test/junit5/cm/ConfigurationExtension.java#L458

This test also fails with getting a `null` value for the configuration parameter *c*:

```
@WithFactoryConfiguration(factoryPid = ConfigAnnotationParamVariants2.MY_PID, name = "test")
public class ConfigAnnotationParamVariants2 {

	static final String MY_PID = "my.pid";

	@Test
	public void test_Parameter_Configuration(@InjectConfiguration(MY_PID) Configuration c) throws Exception {

		Assertions.assertThat(c)
			.isNotNull();

	}
}
```

Here as well the update method on the config admin is called in the codeline linked above. 

I realized that the injecing boolean paramter is always `false` in all described cases. 

I not getting through, what is done here exactly. Further I dont thing that it is possible to distinguish between when someone wants update called on the config admin or what I wanted, that update was not called.

If we see the not-set flag as indicator, to not update the config admin, wehy do we have a line to update nevertheless. This confuses me a bit ;-)

**Comment by maho7791** [comment]
To be clear, I looked for a way to get an empty configuration injected with no `Configuration#update` called upfront.

**Comment by maho7791** [comment]
I can confirm that this works, without any update calls:
https://github.com/osgi/osgi-test/blob/744cb395c1d4bd5407ea172467c4ce37579ed8ba/org.osgi.test.junit5.cm/src/test/java/org/osgi/test/junit5/cm/test/InjectWith.java#L98

**Comment by timothyjward** [comment]
> This test fails with cs == null:
```
static final String MY_PID = "my.fpid";

@Test
@WithFactoryConfiguration(factoryPid = MY_PID)
public void testMethodConfigurationFactoryEmtpy() throws Exception {

	Configuration cs = ConfigUtil.getConfigsByServicePid(ca, MY_PID);
	assertThat(cs).isNotNull();

}
```

This is user error - there is no configuration with `pid` `MY_PID`. There is a factory configuration with `factoryPid` `MY_PID` and an unknown `pid` of the form `MYPID + "~" + "someString"`. There is a similar problem with the other failing test.

> I also debugged both test cases and realized that The update method was called in both tests:

This is required - if you declare your configuration at Class or Test level using a `@WithConfiguration` or `@WithFactoryConfiguration` then it *must* be updated. If not then no configuration will ever be available (i.e. calling `listConfigurations` will not include the configuration you want). The only way to get a configuration which does not have `update` called is by using `@InjectConfiguration`

**Comment by timothyjward** [comment]
> To be clear, I looked for a way to get an empty configuration injected with no Configuration#update calls upfront.

You appear to have found the way to do this:

https://github.com/osgi/osgi-test/blob/744cb395c1d4bd5407ea172467c4ce37579ed8ba/org.osgi.test.junit5.cm/src/test/java/org/osgi/test/junit5/cm/test/InjectWith.java#L98

It is the only way.

**Comment by maho7791** [comment]
> This is required - if you declare your configuration at Class or Test level using a `@WithConfiguration` or `@WithFactoryConfiguration` then it _must_ be updated. If not then no configuration will ever be available (i.e. calling `listConfigurations` will not include the configuration you want). The only way to get a configuration which does not have `update` called is by using `@InjectConfiguration`

Ok, I see your point. 

This is then related to the fact, that all configurations are fetched from config admin list and there is (currently) no other source for empty configuration entries.

I am fine with this current solution. But we should document it :-)

**Comment by timothyjward** [comment]
> I am fine with this current solution. But we should document it :-)

We need a proper documentation site, but for now what we have is this

https://github.com/osgi/osgi-test/blob/744cb395c1d4bd5407ea172467c4ce37579ed8ba/org.osgi.test.junit5.cm/src/main/java/org/osgi/test/common/annotation/config/WithConfiguration.java#L65-L82
