### ISSUE TITLE
Move examples to Java 11?

### ISSUE THREAD

**Issue by timothyjward** [osgi/osgi-test#803]
The latest round of gradle version updates require Java 11, and bnd 7.0.0 requires Java 17. Should we update the examples to use newer versions of Java, or stay with Java 8 and ignore the dependabot updates?

**Comment by timothyjward** [comment]
@rotty3000 @stbischof @bjhargrave @kriegfrj 

Thoughts?

**Comment by stbischof** [comment]
Since it is just examples.. is would go 21

**Comment by timothyjward** [comment]
> Since it is just examples.. is would go 21

We had previously been using a build matrix to prove that we remained compatible with all of the target java versions for osgi-test, which still has a base of Java 8. I would have expected that we might drop 8 from the matrix but keep 11, 17 and 21.

**Comment by stbischof** [comment]
and maybe `LASTEST`

**Comment by timothyjward** [comment]
> I am not sure why you would drop Java 8 support.

The gradle example builds are currently failing to build in CI with Java 8 because Gradle uses a version of Logback that requires Java 11. I'm not proposing to drop Java 8 for osgi-test, but at the moment all PRs have a failing check.

**Comment by bjhargrave** [comment]
Looking at the failed build, the issue is with a Logback update to 1.4 which no longer supports Java 8. Perhaps the answer is to revert https://github.com/osgi/osgi-test/pull/760 and then tell dependabot to ignore logback 1.4 when it next proposes to update to 1.4.

**Comment by bjhargrave** [comment]
> failing to build in CI with Java 8 because Gradle uses a version of Logback that requires Java 11

Gradle does not use this. It is used by the example. I reverted #760 and we will need to tell dependabot to only use logback 1.3.x for the examples.
